### ISSUE TITLE
Works great!

### ISSUE THREAD

**Issue by maxawake** [Seb-sti1/rmtree#5]
Hey! I just wanted to thank you very much for this project! It works perfectly and its the only code which is able to export my notes to PDF. You could maybe add `cairosvg` and `pypdf` as dependencies for your project. Apart from that it works like a charm!

**Comment by Seb-sti1** [comment]
Hello!

Thank you for the feedback, really appreciate it! For `cairosvg`, I totally forgot I installed an apt package, I started a new PR to add an explanation in the readme (https://github.com/Seb-sti1/rmtree/tree/hotfix?tab=readme-ov-file#how-to-install). Regarding `pypdf` I'm not sure what you have in mind. Please let me know if I'm missing something

**Comment by Seb-sti1** [comment]
I'll merge #6 so it'll close this issue but if you think any additional information are needed, just reopen it
